# Generated by Django 3.1.2 on 2020-12-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_posttopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttopic',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='blog.post'),
        ),
    ]
