# Generated by Django 3.1.2 on 2020-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201215_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('posts', models.ManyToManyField(to='blog.Post')),
            ],
        ),
    ]
